BE 피드백 부탁드립니다.
codesquad-member-2020/signup-8 pull request #40
Opened 2020-03-29 06:34 UTC by blossun

BE 기능 완료하여 리뷰 요청드립니다.
FE의 커밋이 합쳐졌는데 분리하기가 어려워서 그냥 보내게 되었습니다. (ㅠㅠ)

질문이 길어서 문서로 만들었습니다!
[BE 질문사항](https://github.com/codesquad-member-2020/signup-8/wiki/%5BBE%5D-%EC%A7%88%EB%AC%B8%EC%82%AC%ED%95%AD)

후기 : 깃이랑 가까워진 듯 싶었는데 다시 멀어진 것 같습니다.... 깃을 이용하지 못하고 팀원이랑 코드를 수작업으로 합쳐서 커밋이 제 계정으로만 남게되었습니다 ㅠㅠㅠ 다음 플젝에서 깃을 활용해볼 수 있도록 하겠습니다.

2020-04-07 11:39 UTC, kyucumber requested changes

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/domain/ResponseResult.java
> +    private boolean valid;
이 `ResponseResult`는 api의 응답 객체로 사용할 목적으로 만드신 것 같네요
이 객체와 valid라는 이름만 봤을땐 어떤 의도로 추가해두신건지 알기 어려운 것 같습니다.

물론 api의 응답에 status code가 무조건 포함되긴 하지만, 차라리 status code같은 값을 포함시키는건 어떨까 싶네요

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiDuplicateController.java
> +    @RequestMapping("")
이렇게 Default로 선언하면 `@Get`인가요?
저처럼 혼란을 느끼는 경우가 있을 수 있으니 `@GetMapping` 등 명확한 어노테이션을 사용하는건 어떨까요?

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiDuplicateController.java
> +        if (phoneNumber != null) {
이런 중복되는 null 체크가 조금 거슬린다 싶으면
userId, email, phonNumber 세개를 가지는 객체를 `@ModelAttribute` 어노테이션을 사용해 받은 뒤
`@Valid` 등의 어노테이션을 통해 검증할 수 있어요

https://www.baeldung.com/spring-boot-bean-validation
위 문서의 4번 항목을 보시면 될 것 같네요

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiUserController.java
> +    @PostMapping("")
("")는 생략해도 될 것 같아요~

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiDuplicateController.java
> +            isDuplicated = isDuplicatedPhoneNumber(phoneNumber);
userId, email, phoneNumber 전부 null이 아니면 그 3개의 값에 대해서 연달아 isDuplicated~~ 라는 메소드를 실행시키면서 `isDuplicated` 변수에 값을 할당하고 있네요

3개 각각 파라미터가 있고 없고에 따라 다른 api 결과를 반환하려고 만드신건가요?

3개 다 넣어주면  맨 마지막 phoneNumber에 대한 결과만이 반환될 것 같은데 괜찮을까요?

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiDuplicateController.java
> +@RequestMapping("/api/duplicate")
유저에 대한 중복 체크로 보이는데요, 지금 user에 대한 중복 체크만 포함되어 있다면

`/api/users` 아래에 두어도 되지 않을까요?

다른 자원에 대한 내용을 표현하는게 아니라 user라는 자원에 대한 값을 표현하는거니 굳이 컨트롤러를 나눌 필욘 없을 것 같아서요

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiUserController.java
> +        log.debug("userId : {}, password : {}", userId, password);
단순히 데이터의 확인 용 로그라면 굳이 남길 필요가 없어 보여요 이런 로그는 개발 단계에서 확인하신 후 삭제하는게 좋아 보입니다.
그리고 password를 로그로 찍는건 굉장히 위험해보이네요 logback 등을 통해 찍은 로그 파일에 비밀번호가 그대로 남아있을 수도 있어요

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/java/com/codesquad/signup08/web/UserController.java
> +public class UserController {
`@Controller` 어노테이션을 통해 정의되어 있어서 View를 리턴해줄 것으로 기대했는데 ResponseEntity를 반환하는 부분도 있고 로그아웃은 위의 `ApiUserController`에도 있는데 여기도 존재해서 좀 헷갈리네요 특별한 의도가 있는게 아니라면 여기는 View(템플릿 엔진 form)를 반환하는 부분만 정의하는게 나을 것 같아요

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/resources/application.properties
> +logging.level.com.codesquad.signup08=DEBUG
혹시 로깅 등의 설정에 관심이 있으시다면 logback에 대해 한번 살펴보세요

https://www.baeldung.com/spring-boot-logging#logback-configuration-logging

위의 4. Logback Configuration Logging 항목을 보시면 됩니다.

2020-04-07 11:39 UTC, tramyu commented on be/signup08/src/main/resources/user-schema.sql
> +      USER_ID VARCHAR(20) NOT NULL,
위에서 중복 체크를 한 것으로 보아 userId, email, phoneNumber는 unique가 되어야 할 것 같아요.

2020-04-07 12:31 UTC, tramyu commented
질문을 미처 못 봐서 따로 아래에 남길게요

1. 동일한 기능 요청에 대해 프론트와 iOS에게 서로 다른 Response 응답을 주도록 구현하였는데 비효율적인 코드 일까요?

피치못할 사정이 있는게 아니라면 동일하게 JSON으로 내려주는게 좋을 것 같아요

2. 잘못된 요청을 처리하기 위해 사용자 정의 Exception을 사용하여도 좋나요?

성공, 실패시 객체를 다르게 내려주고 싶은거라면 Custom Exception을 사용하시지 않아도 괜찮을 것 같네요

```java
    @PostMapping
    public ResponseEntity createEvent(@RequestBody @Valid EventRequestDto eventRequestDto, Errors errors) {
        if (errors.hasErrors()) {
            return ResponseEntity.badRequest().body(errors);
        }
        return ResponseEntity.created(uri).body(resource);
    }
```

그냥 반환을 ResponseEntity로 하고, body에 다른 내용을 담아주면 되지 않을까요?

3. 302로 응답할 때 Body에 내용을 담아주는 것이 좋을까요?

편의상 넣어두셔도 무방하지만, 안 넣어도 될 것 같아요

관련 내용을 첨부해둘게요!

https://stackoverflow.com/questions/8059662/http-302-redirect-is-a-message-body-needed

It's not needed. The RFC2616 however doesn't forbid it as well. Note that it does forbid the message body for certain statuses, such as 204 and 304. If the same were true for 302, then it should surely have been explicitly mentioned.

As far as I know, all modern browsers ignore the message body of a 302 in response to a GET or POST and will directly go to the URL as specified in Location header.

2020-04-21 03:19 UTC, honux77 commented on be/signup08/src/main/java/com/codesquad/signup08/web/ApiUserController.java
> +        log.debug("userId : {}, password : {}", userId, password);
+1

2020-04-21 04:03 UTC, closed without merging